### PR TITLE
1.8 sentieon

### PR DESCRIPTION
**Pull request by chrispyatt**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc/1)

### CODE REVIEW

**Review by woook — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc/1)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @chrispyatt)

___
*[multiqc/utils/config_defaults.yaml, line 377 at r1](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M6j_Zrn9uJfeDWPvf0F:-M6j_Zrn9uJfeDWPvf0G:br3emrc) ([raw file](https://github.com/eastgenomics/multiqc/blob/9062ec42d63a2b8533fe0d84be8236cbb91240f2/multiqc/utils/config_defaults.yaml#L377)):*
> ```
>    - RNA
> ```
Should this be here?

**Review by woook — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc/1)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @chrispyatt)

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc/1)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @woook)

___
*[multiqc/utils/config_defaults.yaml, line 377 at r1](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M6j_Zrn9uJfeDWPvf0F:-M6jc9qhBK-bkWsvy3FZ:b-4cd7s3) ([raw file](https://github.com/eastgenomics/multiqc/blob/9062ec42d63a2b8533fe0d84be8236cbb91240f2/multiqc/utils/config_defaults.yaml#L377)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
>    - RNA
> ```
Should this be here?
</blockquote></details>

Will remove

**Review by woook — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc/1)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @chrispyatt and @woook)

___
*[multiqc/modules/sentieon/InsertSizeMetrics.py, line 3 at r2](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M72_1cpDghpAkjvf_7n:-M72_1cpDghpAkjvf_7o:bfgtbxv) ([raw file](https://github.com/eastgenomics/multiqc/blob/6bfcfe3b5dfbcd7a39b122bfeb731b8bc08ee2a8/multiqc/modules/sentieon/InsertSizeMetrics.py#L3)):*
> ```
> """ MultiQC submodule to parse output from Sentieon InsertSizeMetrics (based on the Picard module of the same name """
> ```
Line too long - please could you fix for whole script
___
*[multiqc/modules/sentieon/InsertSizeMetrics.py, line 8 at r2](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M72Zys8Efs3XYh-CXo7:-M72Zys90vhBVO7_IO_b:b-blbwm1) ([raw file](https://github.com/eastgenomics/multiqc/blob/6bfcfe3b5dfbcd7a39b122bfeb731b8bc08ee2a8/multiqc/modules/sentieon/InsertSizeMetrics.py#L8)):*
> ```
> import re
> ```

Is this used?
___
*[multiqc/modules/sentieon/InsertSizeMetrics.py, line 51 at r2](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M72_EQ5EsgzjIziemFH:-M72_EQ5EsgzjIziemFI:b-gtvl7h) ([raw file](https://github.com/eastgenomics/multiqc/blob/6bfcfe3b5dfbcd7a39b122bfeb731b8bc08ee2a8/multiqc/modules/sentieon/InsertSizeMetrics.py#L51)):*
> ```
> #print s_name
> ```
# print s_name
___
*[multiqc/modules/sentieon/InsertSizeMetrics.py, line 71 at r2](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M72_USnCksQuFXYkBTv:-M72_USnCksQuFXYkBTw:b-ovhgd3) ([raw file](https://github.com/eastgenomics/multiqc/blob/6bfcfe3b5dfbcd7a39b122bfeb731b8bc08ee2a8/multiqc/modules/sentieon/InsertSizeMetrics.py#L71)):*
> ```
> log.debug("Switching commas for points in '{}': {} - {}".format(f['fn'], vals[i], vals[i].replace(',','.')))
> ```
Line is way too long

**Review by woook — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc/1)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @chrispyatt and @woook)

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc/1)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @woook)

___
*[multiqc/modules/sentieon/InsertSizeMetrics.py, line 3 at r2](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M72_1cpDghpAkjvf_7n:-M73Bqr7654ez5qjCNyI:b-896fix) ([raw file](https://github.com/eastgenomics/multiqc/blob/6bfcfe3b5dfbcd7a39b122bfeb731b8bc08ee2a8/multiqc/modules/sentieon/InsertSizeMetrics.py#L3)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> """ MultiQC submodule to parse output from Sentieon InsertSizeMetrics (based on the Picard module of the same name """
> ```
Line too long - please could you fix for whole script
</blockquote></details>

Done.
___
*[multiqc/modules/sentieon/InsertSizeMetrics.py, line 8 at r2](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M72Zys8Efs3XYh-CXo7:-M73BrVv9czHUz_oHE6Z:b-896fix) ([raw file](https://github.com/eastgenomics/multiqc/blob/6bfcfe3b5dfbcd7a39b122bfeb731b8bc08ee2a8/multiqc/modules/sentieon/InsertSizeMetrics.py#L8)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> import re
> ```

Is this used?
</blockquote></details>

Done.
___
*[multiqc/modules/sentieon/InsertSizeMetrics.py, line 51 at r2](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M72_EQ5EsgzjIziemFH:-M73Bsgd8W-0l_wOpqQx:b-896fix) ([raw file](https://github.com/eastgenomics/multiqc/blob/6bfcfe3b5dfbcd7a39b122bfeb731b8bc08ee2a8/multiqc/modules/sentieon/InsertSizeMetrics.py#L51)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> #print s_name
> ```
# print s_name
</blockquote></details>

Done.
___
*[multiqc/modules/sentieon/InsertSizeMetrics.py, line 71 at r2](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M72_USnCksQuFXYkBTv:-M73BtRC-eoW3QNGKIuz:b-896fix) ([raw file](https://github.com/eastgenomics/multiqc/blob/6bfcfe3b5dfbcd7a39b122bfeb731b8bc08ee2a8/multiqc/modules/sentieon/InsertSizeMetrics.py#L71)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> log.debug("Switching commas for points in '{}': {} - {}".format(f['fn'], vals[i], vals[i].replace(',','.')))
> ```
Line is way too long
</blockquote></details>

Done.

**Review by woook — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc/1)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @chrispyatt and @woook)

___
*[multiqc/modules/sentieon/AlignmentSummaryMetrics.py, line 104 at r3](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M737H2d5s3U6eKKdI8L:-M737H2d5s3U6eKKdI8M:bcwl6ya) ([raw file](https://github.com/eastgenomics/multiqc/blob/eb045a41c9da4bba721696582cb439b9d99c948d/multiqc/modules/sentieon/AlignmentSummaryMetrics.py#L104)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
>             if self.sentieon_alignment_metrics[s_name]['CATEGORY'] == 'PAIR':
>                 pdata[s_name][
>                     'total_reads'] = self.sentieon_alignment_metrics[
>                         s_name]['TOTAL_READS']/2
>                 pdata[s_name][
>                     'aligned_reads'] = self.sentieon_alignment_metrics[
>                         s_name]['PF_READS_ALIGNED']/2
>             else:
>                 pdata[s_name][
>                     'total_reads'] = self.sentieon_alignment_metrics[
>                         s_name]['TOTAL_READS']
>                 pdata[s_name][
>                     'aligned_reads'] = self.sentieon_alignment_metrics[
>                         s_name]['PF_READS_ALIGNED']
>                 pdata[s_name][
>                     'unaligned_reads'] = pdata[s_name]['total_reads']-pdata[
>                         s_name]['aligned_reads']
> ```
</details>


This section is losing readability. See https://www.python.org/dev/peps/pep-0008/#indentation some some background.
This is also quite useful: https://stackoverflow.com/questions/5931297/how-would-you-properly-break-this-line-to-match-pep8-rules

Perhaps something like:
if self.sentieon_alignment_metrics[s_name]['CATEGORY'] == 'PAIR':
        pdata[s_name]['total_reads'] = (
            self.sentieon_alignment_metrics[s_name]['TOTAL_READS']/2)
___
*[multiqc/modules/sentieon/AlignmentSummaryMetrics.py, line 136 at r3](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M73HLQK8B_FWpi2Dx4Y:-M73HLQK8B_FWpi2Dx4Z:bgtljgr) ([raw file](https://github.com/eastgenomics/multiqc/blob/eb045a41c9da4bba721696582cb439b9d99c948d/multiqc/modules/sentieon/AlignmentSummaryMetrics.py#L136)):*
> ```
>             description="Please note that Sentieon's read counts are divided\
>                  by two for paired-end data.",
> ```
I prefer:

`description="Please note that Sentieon's read counts are divided \`
`....by two for paired-end data.",`

as this make the white space between divided and by clearer
___
*[multiqc/modules/sentieon/GcBiasMetrics.py, line 39 at r3](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M73JCQBD5Z1lj4fLtf-:-M73JCQBD5Z1lj4fLtf0:bhzpktx) ([raw file](https://github.com/eastgenomics/multiqc/blob/eb045a41c9da4bba721696582cb439b9d99c948d/multiqc/modules/sentieon/GcBiasMetrics.py#L39)):*
> ```
>                         self.sentieon_GCbias_data[s_name][int(
>                             s[gc_col])] = float(s[cov_col])
> ```
This is a bit of a hack. I think ideally you would have fewer nested IFs and then you wouldn't be in a situation with so much indentation.
Let's leave this for now.
___
*[multiqc/modules/sentieon/InsertSizeMetrics.py, line 51 at r2](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M72_EQ5EsgzjIziemFH:-M73K-b25nytJ5eTz3r3:b-li0z6e) ([raw file](https://github.com/eastgenomics/multiqc/blob/6bfcfe3b5dfbcd7a39b122bfeb731b8bc08ee2a8/multiqc/modules/sentieon/InsertSizeMetrics.py#L51)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant that there should be a white space between # and the print s_name comment. 
Markdown formatting kicked in ...
___
*[multiqc/modules/sentieon/InsertSizeMetrics.py, line 71 at r2](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M72_USnCksQuFXYkBTv:-M73KDDp3W4It69vz3t8:b81xuap) ([raw file](https://github.com/eastgenomics/multiqc/blob/6bfcfe3b5dfbcd7a39b122bfeb731b8bc08ee2a8/multiqc/modules/sentieon/InsertSizeMetrics.py#L71)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is better than before but not great. I'll accept this for now.

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc/1)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @woook)

___
*[multiqc/modules/sentieon/AlignmentSummaryMetrics.py, line 104 at r3](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M737H2d5s3U6eKKdI8L:-M73M77EBVDZZXFZZkWm:b-896fix) ([raw file](https://github.com/eastgenomics/multiqc/blob/eb045a41c9da4bba721696582cb439b9d99c948d/multiqc/modules/sentieon/AlignmentSummaryMetrics.py#L104)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
>             if self.sentieon_alignment_metrics[s_name]['CATEGORY'] == 'PAIR':
>                 pdata[s_name][
>                     'total_reads'] = self.sentieon_alignment_metrics[
>                         s_name]['TOTAL_READS']/2
>                 pdata[s_name][
>                     'aligned_reads'] = self.sentieon_alignment_metrics[
>                         s_name]['PF_READS_ALIGNED']/2
>             else:
>                 pdata[s_name][
>                     'total_reads'] = self.sentieon_alignment_metrics[
>                         s_name]['TOTAL_READS']
>                 pdata[s_name][
>                     'aligned_reads'] = self.sentieon_alignment_metrics[
>                         s_name]['PF_READS_ALIGNED']
>                 pdata[s_name][
>                     'unaligned_reads'] = pdata[s_name]['total_reads']-pdata[
>                         s_name]['aligned_reads']
> ```

This section is losing readability. See https://www.python.org/dev/peps/pep-0008/#indentation some some background.
This is also quite useful: https://stackoverflow.com/questions/5931297/how-would-you-properly-break-this-line-to-match-pep8-rules

Perhaps something like:
if self.sentieon_alignment_metrics[s_name]['CATEGORY'] == 'PAIR':
        pdata[s_name]['total_reads'] = (
            self.sentieon_alignment_metrics[s_name]['TOTAL_READS']/2)
</blockquote></details>

Done.
___
*[multiqc/modules/sentieon/AlignmentSummaryMetrics.py, line 136 at r3](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M73HLQK8B_FWpi2Dx4Y:-M73LBqf91J9_I_VMAXG:b-896fix) ([raw file](https://github.com/eastgenomics/multiqc/blob/eb045a41c9da4bba721696582cb439b9d99c948d/multiqc/modules/sentieon/AlignmentSummaryMetrics.py#L136)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
>             description="Please note that Sentieon's read counts are divided\
>                  by two for paired-end data.",
> ```
I prefer:

`description="Please note that Sentieon's read counts are divided \`
`....by two for paired-end data.",`

as this make the white space between divided and by clearer
</blockquote></details>

Done.
___
*[multiqc/modules/sentieon/GcBiasMetrics.py, line 39 at r3](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M73JCQBD5Z1lj4fLtf-:-M73MYrO-OO-1zBpGK3s:b-896fix) ([raw file](https://github.com/eastgenomics/multiqc/blob/eb045a41c9da4bba721696582cb439b9d99c948d/multiqc/modules/sentieon/GcBiasMetrics.py#L39)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
>                         self.sentieon_GCbias_data[s_name][int(
>                             s[gc_col])] = float(s[cov_col])
> ```
This is a bit of a hack. I think ideally you would have fewer nested IFs and then you wouldn't be in a situation with so much indentation.
Let's leave this for now.
</blockquote></details>

Done.
___
*[multiqc/modules/sentieon/InsertSizeMetrics.py, line 51 at r2](https://reviewable.io/reviews/eastgenomics/multiqc/1#-M72_EQ5EsgzjIziemFH:-M73Md9d1TaRjTO1yw2o:b-wefpzc) ([raw file](https://github.com/eastgenomics/multiqc/blob/6bfcfe3b5dfbcd7a39b122bfeb731b8bc08ee2a8/multiqc/modules/sentieon/InsertSizeMetrics.py#L51)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

I meant that there should be a white space between # and the print s_name comment. 
Markdown formatting kicked in ...
</blockquote></details>

It was only a hangover from testing. Not needed.

**Review by woook — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
